apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus-ingressroute
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - match: Host(`{{ .Values.ingress.host }}`) && PathPrefix(`/prometheus`)
    kind: Rule
    services:
    - name: prometheus
      port: {{ .Values.prometheus.service.port }}
    middlewares:
      - name: traefik-auth-admin-middleware
      - name: https-redirect
      
  tls:
    secretName: {{ .Values.tls.cert }}