apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name.elasticsearch }}                       
spec:
  accessModes:
    - ReadWriteMany                    # Mode d'accès au volume persistant
  storageClassName: efs-sc
  volumeName: {{ .Values.pvc.volume.elasticsearch }}         
  resources:
    requests:
      storage: {{ .Values.elasticsearch.storage.capacity }}                    # Capacité de stockage demandée pour le volume