apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pvc                       
spec:
  accessModes:
    - ReadWriteOnce                    # Mode d'accès au volume persistant
  storageClassName: efs-sc
  volumeName: efs-pv         
  resources:
    requests:
      storage: {{ .Values.elasticsearch.storage.capacity }}                    # Capacité de stockage demandée pour le volume