apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name.elasticsearch }}                       
spec:
  accessModes:
    - ReadWriteOnce                    # Mode d'accès au volume persistant
  storageClassName: local-path      
  resources:
    requests:
      storage: {{ .Values.elasticsearch.storage.capacity }}                    # Capacité de stockage demandée pour le volume
