apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pv-claim
  namespace: monitoring
spec:
  storageClassName: efs-sc
  volumeName: efs-pv-grafana
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi