apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: joel.lourenco.pro@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-issuer-account-key
    solvers:
      - http01:
          ingress:
            serviceType: ClusterIP
            ingressClassName: traefik
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt
  namespace: {{ .Values.namespace }}
spec:
  commonName: {{ .Values.ingress.host }}
  secretName: letsencrypt
  dnsNames:
    - {{ .Values.ingress.host }}
  issuerRef:
    kind: Issuer
    name: letsencrypt