# Ce fichier YAML définit une réclamation de volume persistant (PVC) nommée "db-pvc"
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc                       
spec:
  accessModes:
    - ReadWriteOnce                    # Mode d'accès au volume persistant
  storageClassName: efs-sc
  volumeName: efs-pv-db        
  resources:
    requests:
      storage: {{ .Values.db.storage.capacity }}                    # Capacité de stockage demandée pour le volume