# Ce fichier YAML définit une réclamation de volume persistant (PVC) nommée "db-pvc"
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name.postgres }}                       
spec:
  accessModes:
    - ReadWriteOnce                 # Mode d'accès au volume persistant
  storageClassName: local-path 
  resources:
    requests:
      storage: {{ .Values.db.storage.capacity }}                    # Capacité de stockage demandée pour le volume
