apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: monitoring
  annotations: 
    kubernetes.io/ingress.class: traefik
  name: monitoring-stack-ingress
  labels:
    name: monitoring-stack-ingress

spec:
  rules:
  - host: grafana.kbnhvn-project.eu
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: monitoring-stack-grafana 
            port: 
              number: 80

  - host: prom.kbnhvn-project.eu
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: monitoring-stack-kube-prom-prometheus 
            port: 
              number: 9090