apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-ingressroute
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`{{ .Values.grafana.host }}`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: grafana
      port: {{ .Values.grafana.service.port }}
      
  # tls:
  #   secretName: {{ .Values.tls.cert }}