apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc                       
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  volumeName: efs-pv-grafanas        
  resources:
    requests:
      storage: {{ .Values.grafana.storage.capacity }}