apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  ports:
    - protocol: TCP
      targetPort: 3000
      port: {{ .Values.grafana.service.port }}
  selector:
    app: grafana
  type: {{ .Values.grafana.service.type }}