apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus-ingressroute
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`{{ .Values.prometheus.host }}`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: prometheus
      port: {{ .Values.prometheus.service.port }}
      