apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc                       
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  volumeName: efs-pv-prom        
  resources:
    requests:
      storage: {{ .Values.prometheus.storage.capacity }}