apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  ports:
    - protocol: TCP
      targetPort: 9090
      port: {{ .Values.prometheus.service.port }}
  selector:
    app: prometheus
  type: {{ .Values.prometheus.service.type }}