namespace: prod

web:
  repository: kbnhvn/web-prod
  tag: latest

data:
  tag: latest

nginx:
  tag: latest

ingress:
  host: app.kbnhvn-devops-project.work

role:
  name: traefik-role-prod

roleBinding:
  name: traefik-role-binding-prod