namespace: dev

web:
  repository: kbnhvn/web-dev
  tag: latest

data:
  tag: latest

nginx:
  tag: latest

ingress:
  host: dev.kbnhvn-devops-project.work

role:
  name: traefik-role-dev

roleBinding:
  name: traefik-role-binding-dev

tls:
  cert: dev-cert

pvc:
  name:
    postgres: db-pvc-dev
    elasticsearch: elasticsearch-pvc-dev
    prometheus: prometheus-pvc-dev
    grafana: grafana-pvc-dev
  volume: 
    postgres: efs-pv-db-dev
    elasticsearch: efs-pv-es-dev
    prometheus: efs-pv-prom-dev
    grafana: grafana-pvc-grafana-dev