namespace: prod

web:
  repository: kbnhvn/web-prod
  tag: latest

data:
  tag: latest

nginx:
  tag: latest

ingress:
  host: app.kbnhvn-devops-project.work

role:
  name: traefik-role-prod

roleBinding:
  name: traefik-role-binding-prod

tls:
  cert: app-cert

pvc:
  name:
    postgres: db-pvc
    elasticsearch: elasticsearch-pvc
    prometheus: prometheus-pvc
    grafana: grafana-pvc
  volume: 
    postgres: efs-pv-db
    elasticsearch: efs-pv-es
    prometheus: efs-pv-prom
    grafana: grafana-pvc-grafana