apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudns-issuer
spec:
  acme:
    email: joel.lourenco.pro@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: issuer-account-key
    solvers:
      - dns01:
        webhook:
        groupName: acme.ixon.cloud
        solverName: cloudns
          ingress:
            class: traefik
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt
spec:
  commonName: app.kbnhvn-project.eu
  secretName: letsencrypt
  issuerRef:
    name: cloudns-issuer
    kind: ClusterIssuer
  dnsNames:
    - "app.kbnhvn-project.eu" 