apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudns-issuer-prod
spec:
  acme:
    email: joel.lourenco.pro@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: issuer-account-key-prod
    solvers:
      - http01:
          ingress:
            serviceType: ClusterIP
            ingressClassName: traefik
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt
spec:
  commonName: app.kbnhvn-project.eu
  secretName: letsencrypt
  issuerRef:
    name: cloudns-issuer-prod
    kind: ClusterIssuer
  dnsNames:
    - "app.kbnhvn-project.eu" 