apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: joel.lourenco.pro@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      name: cloudflare-issuer-account-key
    solvers:
    - dns01:
        cloudflare:
          email: joel.lourenco.pro@gmail.com
          apiTokenSecretRef:
            name: cloudflare-token
            key: api-token
      selector:
        dnsZones:
        - 'kbnhvn-devops-project.work'
        - '*.mydomdom.org'
        
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-cert
  namespace: cert-manager
spec:
  commonName: app.kbnhvn-devops-project.work
  secretName: app-cert
  dnsNames:
    - app.kbnhvn-devops-project.work
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dev-cert
  namespace: cert-manager
spec:
  commonName: dev.kbnhvn-devops-project.work
  secretName: dev-cert
  dnsNames:
    - dev.kbnhvn-devops-project.work
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: global-cert
  namespace: cert-manager
spec:
  commonName: app.kbnhvn-devops-project.work
  secretName: global-cert
  dnsNames:
    - app.kbnhvn-devops-project.work
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
