apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: joel.lourenco.pro@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      name: cloudflare-issuer-account-key
    solvers:
    - dns01:
        cloudflare:
          email: joel.lourenco.pro@gmail.com
          apiTokenSecretRef:
            name: cloudflare-token
            key: api-token
      selector:
        dnsZones:
        - 'kbnhvn-devops-project.work'
        - '*.kbnhvn-devops-project.work'
        